// @ts-check

/* eslint-disable  @typescript-eslint/no-var-requires */

const { defineConfig } = require('eslint-define-config');

// const bestPractices = require('./eslint/best-practices');
const { error } = require('./types');

const configuration = defineConfig({
  extends: [
    'eslint:recommended',
  ],
  rules: {
    // ...bestPractices.rules,

    // Possible Problems
    // These rules relate to possible logic errors in code:

    'array-callback-return': [
      error,
      {
        allowImplicit: true,
        checkForEach: true,
      },
    ],
    'no-await-in-loop': error,
    // 'no-constant-binary-expression': off,
    // 'no-constructor-return': off,
    // 'no-duplicate-imports': off,
    // 'no-new-native-nonconstructor': off,
    // 'no-promise-executor-return': off,
    // 'no-self-compare': off,
    // 'no-template-curly-in-string': off,
    // 'no-unmodified-loop-condition': off,
    // 'no-unreachable-loop': off,
    // 'no-unused-private-class-members': off,
    // 'no-use-before-define': off,
    // 'require-atomic-updates': off,

    // Suggestions
    // These rules suggest alternate ways of doing things:

    // 'accessor-pairs': off,
    // 'arrow-body-style': off,
    // 'block-scoped-var': off,
    // 'camelcase': off,
    // 'capitalized-comments': off,
    // 'class-methods-use-this': off,
    // 'complexity': off,
    // 'consistent-return': off,
    // 'consistent-this': off,
    // 'curly': off,
    // 'default-case': off,
    // 'default-case-last': off,
    // 'default-param-last': off,
    // 'dot-notation': off,
    // 'eqeqeq': off,
    // 'func-name-matching': off,
    // 'func-names': off,
    // 'func-style': off,
    // 'grouped-accessor-pairs': off,
    // 'guard-for-in': off,
    // 'id-denylist': off,
    // 'id-length': off,
    // 'id-match': off,
    // 'init-declarations': off,
    // 'logical-assignment-operators': off,
    // 'max-classes-per-file': off,
    // 'max-depth': off,
    // 'max-lines': off,
    // 'max-lines-per-function': off,
    // 'max-nested-callbacks': off,
    // 'max-params': off,
    // 'max-statements': off,
    // 'multiline-comment-style': off,
    // 'new-cap': off,
    // 'no-alert': off,
    // 'no-array-constructor': off,
    // 'no-bitwise': off,
    // 'no-caller': off,
    // "no-case-declarations": error,
    // 'no-confusing-arrow': off,
    // 'no-console': off,
    // 'no-continue': off,
    // 'no-delete-var': error,
    // 'no-div-regex': off,
    // 'no-else-return': off,
    'no-empty': [
      error,
      {
        allowEmptyCatch: true,
      },
    ],
    // 'no-empty-function': off,
    // 'no-empty-static-block': off,
    // 'no-eq-null': off,
    'no-eval': error,
    // 'no-extend-native': off,
    // 'no-extra-bind': off,
    'no-extra-boolean-cast': [
      error,
      {
        enforceForLogicalOperands: true,
      },
    ],
    // 'no-extra-label': off,
    // 'no-extra-semi': error,
    // 'no-floating-decimal': off,
    // 'no-global-assign': error,
    // 'no-implicit-coercion': off,
    // 'no-implicit-globals': off,
    // 'no-implied-eval': off,
    // 'no-inline-comments': off,
    // 'no-invalid-this': off,
    // 'no-iterator': off,
    // 'no-label-var': off,
    // 'no-labels': off,
    // 'no-lone-blocks': off,
    // 'no-lonely-if': off,
    // 'no-loop-func': off,
    // 'no-magic-numbers': off,
    // 'no-mixed-operators': off,
    // 'no-multi-assign': off,
    // 'no-multi-str': off,
    // 'no-negated-condition': off,
    // 'no-nested-ternary': off,
    // 'no-new': off,
    // 'no-new-func': off,
    // 'no-new-object': off,
    // 'no-new-wrappers': off,
    // 'no-nonoctal-decimal-escape': error,
    // 'no-octal': error,
    // 'no-octal-escape': off,
    // 'no-param-reassign': off,
    // 'no-plusplus': off,
    // 'no-proto': off,
    // 'no-redeclare': error,
    // 'no-regex-spaces': error,
    // 'no-restricted-exports': off,
    // 'no-restricted-globals': off,
    // 'no-restricted-imports': off,
    // 'no-restricted-properties': off,
    // 'no-restricted-syntax': off,
    // 'no-return-assign': off,
    // 'no-return-await': off,
    // 'no-script-url': off,
    // 'no-sequences': off,
    // 'no-shadow': off,
    // 'no-shadow-restricted-names': error,
    // 'no-ternary': off,
    // 'no-throw-literal': off,
    // 'no-undef-init': off,
    // 'no-undefined': off,
    // 'no-underscore-dangle': off,
    // 'no-unneeded-ternary': off,
    // 'no-unused-expressions': off,
    // 'no-unused-labels': error,
    // 'no-useless-call': off,
    // 'no-useless-catch': error,
    // 'no-useless-computed-key': off,
    // 'no-useless-concat': off,
    // 'no-useless-constructor': off,
    // 'no-useless-escape': error,
    // 'no-useless-rename': off,
    // 'no-useless-return': off,
    // 'no-var': off,
    // 'no-void': off,
    // 'no-warning-comments': off,
    // 'no-with': error,
    // 'object-shorthand': off,
    // 'one-var': off,
    // 'one-var-declaration-per-line': off,
    // 'operator-assignment': off,
    // 'prefer-arrow-callback': off,
    // 'prefer-const': off,
    // 'prefer-destructuring': off,
    // 'prefer-exponentiation-operator': off,
    // 'prefer-named-capture-group': off,
    // 'prefer-numeric-literals': off,
    // 'prefer-object-has-own': off,
    // 'prefer-object-spread': off,
    // 'prefer-promise-reject-errors': off,
    // 'prefer-regex-literals': off,
    // 'prefer-rest-params': off,
    // 'prefer-spread': off,
    // 'prefer-template': off,
    // 'quote-props': off,
    // 'radix': off,
    // 'require-await': off,
    // 'require-unicode-regexp': off,
    // 'require-yield': error,
    // 'sort-imports': off,
    // 'sort-keys': off,
    // 'sort-vars': off,
    'spaced-comment': error,
    // 'strict': off,
    // 'symbol-description': off,
    // 'vars-on-top': off,
    // 'yoda': off,

    // Layout & Formatting
    // These rules care about how the code looks rather than how it executes:

    'array-bracket-newline': [
      error,
      'consistent',
    ],
    'array-bracket-spacing': error,
    'array-element-newline': [
      error,
      'consistent',
    ],
    'arrow-parens': error,
    'arrow-spacing': error,
    'block-spacing': error,
    'brace-style': error,
    'comma-dangle': [
      error,
      'always-multiline',
    ],
    'comma-spacing': error,
    'comma-style': error,
    'computed-property-spacing': error,
    'dot-location': error,
    // 'eol-last': off,
    // 'func-call-spacing': off,
    // 'function-call-argument-newline': off,
    // 'function-paren-newline': off,
    // 'generator-star-spacing': off,
    // 'implicit-arrow-linebreak': off,
    'indent': [
      error,
      2,
    ],
    'jsx-quotes': [
      error,
      'prefer-single',
    ],
    'key-spacing': error,
    // 'keyword-spacing': off,
    // 'line-comment-position': off,
    // 'linebreak-style': off,
    // 'lines-around-comment': off,
    // 'lines-between-class-members': off,
    'max-len': [
      error,
      {
        code: 100,
        ignoreComments: false,
        ignoreUrls: false,
        ignoreStrings: false,
        ignoreTemplateLiterals: false,
        ignoreRegExpLiterals: false,
      },
    ],
    // 'max-statements-per-line': off,
    // 'multiline-ternary': off,
    // 'new-parens': off,
    // 'newline-per-chained-call': off,
    'no-extra-parens': error,
    // 'no-mixed-spaces-and-tabs': error,
    'no-multi-spaces': error,
    'no-multiple-empty-lines': [
      error,
      {
        max: 1,
        maxEOF: 0,
        maxBOF: 0,
      },
    ],
    'no-tabs': error,
    'no-trailing-spaces': error,
    // 'no-whitespace-before-property': off,
    // 'nonblock-statement-body-position': off,
    // 'object-curly-newline': off,
    'object-curly-spacing': [
      error,
      'always',
    ],
    // 'object-property-newline': off,
    // 'operator-linebreak': off,
    // 'padded-blocks': off,
    // 'padding-line-between-statements': off,
    // 'quotes': off,
    // 'rest-spread-spacing': off,
    'semi': error,
    // 'semi-spacing': off,
    // 'semi-style': off,
    // 'space-before-blocks': off,
    // 'space-before-function-paren': off,
    // 'space-in-parens': off,
    // 'space-infix-ops': off,
    // 'space-unary-ops': off,
    // 'switch-colon-spacing': off,
    // 'template-curly-spacing': off,
    // 'template-tag-spacing': off,
    // 'unicode-bom': off,
    // 'wrap-iife': off,
    // 'wrap-regex': off,
    // 'yield-star-spacing': off,
  },
});

const { extends: configurationExtensions, rules: configurationRules } = configuration;

/** @type { import('./types').Extensions } */
const extensions = configurationExtensions ?? [];

/** @type { import('./types').Rules } */
const rules = configurationRules ?? {};

module.exports = { extensions, rules };
